name:                polysemy-kvstore-jsonfile
version:             0.1.1.0
git:                 https://gitlab.com/homotopic-tech/polysemy-kvstore-jsonfile
license:             MIT
author:              "Daniel Firth"
maintainer:          "dan.firth@homotopic.tech"
copyright:           "2020 Daniel Firth"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Run a KVStore as a single json file in polysemy.
category:            Polysemy

dependencies:
- aeson >= 1.0 && < 1.6
- base >= 4.7 && < 4.16
- containers >= 0.5 && < 0.7
- exceptions >= 0.10.0 && < 0.11
- extra >= 1.0 && < 1.8
- path >= 0.7 && < 0.10
- polysemy >= 1.3.0.0 && < 1.7
- polysemy-kvstore >= 0.1.2.0 && < 0.2
- unliftio-path >= 0.0.2.0 && < 0.1

library:
  source-dirs: src
